name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64
          - aarch64

    steps:
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: build
        run: |
          make ${{ matrix.platform }}

      - name: test
        run: |
          make test-${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-SqldefRole-CAF6QAE95D0P
      - name: upload
        run: |
          make upload
