name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64
          - aarch64

    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v5
      - name: build
        run: |
          make ${{ matrix.platform }}

      - name: test
        run: |
          make test-${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-SqldefRole-CAF6QAE95D0P
          role-session-tagging: true
      - name: upload
        run: |
          make upload
