name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: actionlint
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0

  rpmlint:
    name: runner / rpmlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: rpmlint
        uses: shogo82148/actions-rpmlint@0b55d29c2e1d3c880a0163fec05d12aba77bfb67 # v0.1.0
        with:
          rpmlint_flags: rpmbuild/SPECS/h2o.spec
