name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: actionlint
        uses: reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8 # v1.76.0

  rpmlint:
    name: runner / rpmlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: rpmlint
        uses: shogo82148/actions-rpmlint@27ca80455b83789769b975db5b0869e6f0b72ccc # v0.2.0
        with:
          rpmlint_flags: rpmbuild/SPECS/sqldef.spec
