name: reviewdog
on: [pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0

  rpmlint:
    name: runner / rpmlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: rpmlint
        uses: shogo82148/actions-rpmlint@0b55d29c2e1d3c880a0163fec05d12aba77bfb67 # v0.1.0
        with:
          rpmlint_flags: rpmbuild/SPECS/h2o.spec
