name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "32 20 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - id: update
        name: update
        run: |
          make update

      - uses: shogo82148/actions-commit-and-create-pr@v1
        with:
          commit-message: bump sqldef v${{ steps.update.outputs.latest-version }}
