name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "32 20 * * *"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: generate
        uses: shogo82148/actions-github-app-token@84232dc4d9bd875d4dd83e3e5c4705db1c98a997 # v1.3.1
      - uses: shogo82148/actions-setup-perl@3d3cb73ca65d657a809d97eab324d4e4f140bf5e # v1.42.0
        with:
          perl-version: "5.38"
      - id: update
        name: update
        run: |
          make update
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: shogo82148/actions-commit-and-create-pr@b1322fe9da4037e9720e34ea221997cffcd3498d # v1.1.4
        with:
          github-token: ${{ steps.generate.outputs.token }}
          commit-message: bump sqldef v${{ steps.update.outputs.latest-version }}
